Components/BuzzController: remove unused dependencies
Those unused dependencies trigger build errors:

  > tsc -b && vite build

  src/Components/BuzzController.tsx:4:64 - error TS6133: 'IoStar' is declared but its value is never read.

  4 import { IoCheckmarkDoneSharp, IoCheckmarkSharp, IoCloseSharp, IoStar, IoStarHalf, IoStarOutline } from "react-icons/io5";
                                                                   ~~~~~~

  src/Components/BuzzController.tsx:4:72 - error TS6133: 'IoStarHalf' is declared but its value is never read.

  4 import { IoCheckmarkDoneSharp, IoCheckmarkSharp, IoCloseSharp, IoStar, IoStarHalf, IoStarOutline } from "react-icons/io5";
                                                                           ~~~~~~~~~~

  src/Components/BuzzController.tsx:4:84 - error TS6133: 'IoStarOutline' is declared but its value is never read.

  4 import { IoCheckmarkDoneSharp, IoCheckmarkSharp, IoCloseSharp, IoStar, IoStarHalf, IoStarOutline } from "react-icons/io5";
                                                                                       ~~~~~~~~~~~~~

  Found 3 errors.

Signed-off-by: Alexis Lothoré <alexis.lothore@gmail.com>