components: remove unused React import
When trying to build the admin front pages with the following
commandline:

  usr/bin/npm --prefix <admin-front-dir> install
  usr/bin/npm --prefix <admin-front-dir> run build

the build fails with the following error:

  > tsc -b && vite build

  src/Components/AdminHome.tsx:1:1 - error TS6133: 'React' is declared but
  its value is never read.

  1 import React from "react";
    ~~~~~~~~~~~~~~~~~~~~~~~~~~

  src/Components/ImportPlaylist.tsx:1:8 - error TS6133: 'React' is
  declared but its value is never read.

  1 import React, { useContext, useState } from "react";
           ~~~~~

  Found 2 errors.

Fix the errors by getting rid of the unused imports.

Signed-off-by: Alexis Lothoré <alexis.lothore@gmail.com>